### ISSUE TITLE
active branch discussion

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#2]
The initial schema plugin is arriving as https://github.com/metadata101/iso19139.ca.HNAP/pull/1 against branch 3.8.x.

We should decide which active branches to maintain:

* **3.6.x** is used by Federal Geospatial Portal (FGP)
* 3.6.x-ec used by Environment Climate Change Canada (ECCC)
* 3.8.x not in use
* **3.10.x** stable branch of core-geonetwork (GeoCat Live, DFO)
* **master** not in use, available to track core-geonetwork master

**Comment by jodygarnett** [comment]
@josegar74 how should we proceed, I think we already know of some small changes needed for 3.10.x compatibility.

**Comment by jodygarnett** [comment]
Going to recommend:

1) start with 3.6.x branch for FGP
2) leave the 3.8.x branch empty (@ianwallen can provide direction here)
3) @josegar74 can work on a 3.10.x branch

**Comment by ianwallen** [comment]
The code that you are currently adding may only work with the 3.8 branch.  I don't think FGP is ready so  submit their changes or if there are plans for them to submit the code as it is specific to there application (may want to verify with them).    So I would recommend the 3.8 branch be the active branch.

**Comment by jodygarnett** [comment]
We have some coordination with FGP, the larger goal here is to combine forces on a common activity.

**Comment by ianwallen** [comment]
We are about to start switching to the 3.10 release (probably after the 3.10.2 release).
So we can probably change the default branch so that it is no longer 3.8

Just wondering, if we want to follow the geonetwork core branch model.  We could place all the 3.10 code into the master and commit to it with cherry picks to the 3.10 release?

**Comment by ianwallen** [comment]
I would also like to propose that we use Travis builds to verify that the commits are not breaking the integration into the geonetwork.   Theoretically, there should be little impact on the plugin build within geonetwork core.- however since this repo was created, I don't believe there has been any successful build with all unit test.  I found one issue related to the autodetect that was causing issues and I have a pull request to fix this.  However after these changes, there are still some errors in the unit test once the plugin has been merged with geonetwork core.  Once these issues are fixed it would be nice to know that similar issues don't come up again.

**Comment by jodygarnett** [comment]
Due to the design of geonetwork we have found issues that need to be resolved in geonetwork core and then back ported to 3.10.x for the plugin to work. Perhaps we can do a better job cross checking the various pull requests from HNAP issues.

Use of travis or a build server is a very good idea; perhaps open a separate ticket (either here or on geonetwork-core if it is a change appropriate to all the plugins).

**Comment by jodygarnett** [comment]
Can we remove 3.8.x as an active branch now? Has DFO complete updating to 3.10.x?

**Comment by ianwallen** [comment]
You can make the 3.10.x the default branch.  Is there a reason you want to remove the 3.8.x branch?  

There are pull request for bug fixes that target the 3.8.x branch which should also be cherry picked to the 3.10.x branch once they have been approved.

DFO is still working on the 3.10.x upgrade and we don't plan on contributing any new code to the 3.8.x branch.

**Comment by jodygarnett** [comment]
I would just like to reflect what is under active development (and thus should be considered for porting any fixes).

**Comment by ianwallen** [comment]
I believe we should switch the default branch to 3.10.x now. I would do this but I don't believe I have the privileges or I cannot find the location to make the change.

**Comment by jodygarnett** [comment]
I wanted to bring this [proposal](https://github.com/geonetwork/core-geonetwork/wiki/Host-Geonetwork-artifacts-on-repo.osgeo.org-(Nexus-Artifactory-Repo)) to everyone's attention as it would be very useful for our HNAP group.

**Comment by geothorne** [comment]
has this issue been resolved?

**Comment by jodygarnett** [comment]
Updated to indicate 3.11.x as active.

**Comment by ianwallen** [comment]
@jodygarnett 

I personally don't like having a 3.11.x branch as it is never released.  It looks like Geonetwork core had tried that in the past and then abandoned the idea and simply use master

It looks like the geonetwork core is using something similar to the following gitflow branch management
http://blogs.stonesteps.ca/showpost.aspx?pid=67
Where master contains all development and dedicated release branch are used to manage the version changes.

As there will never be a 3.11.0 release, I don't believe it  makes sense to create a 3.11.x branch.

I believe it would be better to follow Geonetwork core lead. We should apply all our changes for 3.11.x to the master and once it is decided to create a 3.12.x then we create the same branch.

I find the one thing that I'm on the fence is how we move changes between master and the release branch.  The link above seems to indicate that changes would be applied to the dedicated release branch and then merged back into the master.  While geonetwork has everything added to the master and then they cherry pick to the dedicated release branch.  It seems like the merge would be the better approach but maybe there was issues in the past and they have there reason for doing cherry picks instead?

**Comment by geothorne** [comment]
@jodygarnett  and @ianwallen I think I need to understand this more to have any opinion or suggestion. Maybe an item for verbal discussion?

**Comment by jodygarnett** [comment]
@ianwallen should I rename it to "master" to match core-geonetwork "master" branch?

With 4701 being merged on core-geonetwork master I used the above 3.11.x branch to test the `add-schema.sh` script.

**Comment by ianwallen** [comment]
@jodygarnett 
I think it would be better if we matched the branched between geonetwork core and this repo.  So yes, my preference is that this would be master.  Note that master already exists so this would not be a rename. - I will let you figure this out.

Should we change the default branch to master? All changes would be pushed to master and then cherry picked into 3.10.x like it is done on geonetwork core.   Or it may be easier if we push changes to the 3.10.x like we are currently doing and do merges to the master instead of cherry picks which may be easier?

Maybe we can wait and see what @josegar74 suggest.

**Comment by jodygarnett** [comment]
I am fine to rename, will need to change the example provided by `add-schema.sh` script also.

**Comment by jodygarnett** [comment]
Let's confirm with @josegar74 and do this work next week

**Comment by jodygarnett** [comment]
Notes on *master* branch:

* likely to change to *main* in future (see Black lives matters changes at git and github level)
* not sure we expect this to be maintained if nobody is running/testing master
* trade off: continual overhead of backporting, or larger effort to upgrade/test when 3.12 is released

tradeoff discussion:

- Ian: Consider working on 3.10.x , and forward port changes to "master" for local testing against "core-geonetwork".
- Jody: Use of *provided* for core geonetwork dependencies allows cross testing across branches.

Action:

* Ian can you try use of provided for testing against master and 3.10.x?
* Jody recommend we treat "master" as throwaway and make it real when there is a release candidate

**Comment by jodygarnett** [comment]
Note core-geonetwork `4.0.x` branch which is now released ... it is unclear what is next. My assumption is:

* `4.0.x` ➡️ `main`
* `master` ➡️ `3.12.x`

**Comment by ianwallen** [comment]
@jodygarnett 
I wonder how the upgrade paths are going to work if GN continues to support multiple active version as you indicate.
I believe GN only supports a linear upgrade path with the migration scripts.

Since 3.10.4, there has also been a release 4.0
As there are 2 version it can mess up the migration path in the following scenario

3.10.4  ➡️ 3.10.5  ➡️ 3.10.6  ➡️ 4.0.0

In this case I believe 4.0.0 does not know about the migration scripts for 3.10.5 and 3.10.6.  If 3.10.5 or 3.10.6 happen to apply the same migration scripts as the 4.0.0 then when upgrading to 4.0.0 the migration scripts will fail.

GN would almost need to update the migration logic so that 

- 4.0.0 would indicate that that it can only upgrade from 3.10.4 and fail to start if > 3.10.4 and < 4
- 4.0.1 can indicate that it can only upgrade from 3.10.5 and fail to start if > 3.10.5 and < 4
- 4.0.2 can indicate that it can only upgrade from 3.10.6 and fail to start if > 3.10.6 and < 4
- and so on....

So in the case above(upgrading to 4.0.0 from 3.10.6), the system would fail to start and it would tell the user that they are using 3.10.5 and their upgrade path needs to be to 4.0.1.

**Comment by jodygarnett** [comment]
That is tricky, this may be a question for @josegar74 and the GeoNetwork PSC: 

Since each branch has its own migration scripts it may be manageable if done in stages. So if we are looking ahead to a `3.0.6` and a `4.0.1` release:

1. The `3.x` branch could always contain the stable 3.x upgrade steps:

   *  `3.0.4` ➡️ `3.0.5` ➡️ `3.0.6` update

2. And the `4.x` branch could focus on migrating from the latest `3.x` step, along side any `4.x` updates:

   * `3.0.6` ➡️ `4.0.1` migration 
   * `4.0.0` ➡️ `4.0.1` update

So migration procedure would always be to update to the latest 3.x release, and then migration to 4.x

**Comment by jodygarnett** [comment]
Moving discussion to https://github.com/metadata101/iso19139.ca.HNAP/discussions/197
