### ISSUE TITLE
Format dropdown list not displayed correctly

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#287]
When selecting the resource format in the file store, it is not showing the dropdown box correctly.  It seems as if there are more options that cannot be reached.

![image](https://user-images.githubusercontent.com/1868233/195071155-194d2623-e695-4842-ac89-bf1655bdcaf2.png)

We had users who wanted to browse the full list but were not able to.

It may require a CSS fix? And possibly increase the size of the selection list.

**Comment by wangf1122** [comment]
I had looked into this issue. According to the Geonetwork document, we could do some configuration to this https://github.com/metadata101/iso19139.ca.HNAP/blob/3b4137b971142bd133040a2e6b36c20595bc6671/src/main/plugin/iso19139.ca.HNAP/config/associated-panel/default.json#L44-L49

But I had no luck so far.

**Comment by wangf1122** [comment]
There seems to be a bug in geonetwork where the data-number-of-suggestions is missing from the multientrycombiner_onlineresourcesdescription.html widget. I will submit a PR (https://github.com/geonetwork/core-geonetwork/pull/6655) for it. Otherwise, that UI module won't take this configuration of numberOfSuggestions
