### ISSUE TITLE
administrativeArea issues importing FGP data.

### ISSUE THREAD

**Issue by ianwallen** [metadata101/iso19139.ca.HNAP#317]
Issue importing data from FGP

When importing records from FGP it was noticed that we get items like the following

**Missing gmd:PT_FreeText**

```
<gmd:administrativeArea xsi:type="gmd:PT_FreeText_PropertyType">
           <gco:CharacterString>Québec</gco:CharacterString>
</gmd:administrativeArea>
```

**empty gco:CharacterString**

```
                            <gmd:administrativeArea gco:nilReason="missing" xsi:type="gmd:PT_FreeText_PropertyType">
                                    <gco:CharacterString/>
                                    <gmd:PT_FreeText>
                                       <gmd:textGroup>
                                          <gmd:LocalisedCharacterString locale="#eng">Québec</gmd:LocalisedCharacterString>
                                       </gmd:textGroup>
                                    </gmd:PT_FreeText>
                                 </gmd:administrativeArea>
```

**Incorrect province name - Québec should be Quebec in English**
```
                            <gmd:administrativeArea gco:nilReason="missing" xsi:type="gmd:PT_FreeText_PropertyType">
                                    <gco:CharacterString/>
                                    <gmd:PT_FreeText>
                                       <gmd:textGroup>
                                          <gmd:LocalisedCharacterString locale="#eng">Québec</gmd:LocalisedCharacterString>
                                       </gmd:textGroup>
                                    </gmd:PT_FreeText>
                                 </gmd:administrativeArea>
```

**Comment by ianwallen** [comment]
@bo-lu - you may want to investigate these issues within FGP

**Comment by bo-lu** [comment]
There is actually no validation happening on the province field and it is optional. For example, if someone manually edited the XML any FreeText would validate. So for 1), I'm not sure if this is a bug since the Province/Territory is optional, 2) I would classify this as a bug and likely a remnant from v2.10, and 3) another remnant from v2.10. Depending how many records have this issue, we can fix those via SQL.

Right now the autocomplete feature on GN 3.6 will populate the correct province/territory in both English and French. Since the autocomplete is new in 3.6, I'm thinking this issue stems from the previous 2.10 version.
