### ISSUE TITLE
Any interest in maven build profiles to include additional / replacement content (thesauri,xslt,etc...)

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#45]
Forgive me if I word this wrong, I am pulling on a piece of string to describe a challenge.

The HNAP schema also has some keywords thesauri built-in

The HNAP schema (core-geonetwork) has a workflow for adding additional keyword thesauri:

1. Use the admin menu to upload a thesauri

2. Define a template that references the new thesauri 

3. Any metadata record created from that template can access and use the keywords defined

I would like to discuss how we can manage additional optional thesauri in the plugin, perhaps as a build profile, in order to manage these under version control. Would such a proposal be welcome?

**Comment by ianwallen** [comment]
Are you asking for geonetwork core or for the HNAP profile?
Are you suggesting something like Metadata 101 for thesauri so that the thesauri could be shared with the public?

I'm not sure if geonetwork has an API for uploading new thesauri (if not, it should not be too difficult to create) -   a script/program could be created for pushing new thesauri and templates using the API..   Or we could use a script similar to the add-schema.sh from geonetwork core to import thesauri into the current profile.

So far we have not had the requirement to deviate from the existing HNAP thesauri, however, we also did not spend much time on the subject.  I do believe at some point we will get a request to include custom thesauri into our installation so I believe this proposal sounds like it could be useful for us in the future.

**Comment by jodygarnett** [comment]
Hello Ian,

Sorry my discussion topic is not immediately clear, if you wish to add additional keywords (perhaps for your department) it *is* possible via using the admin menu to upload.

Some thesauri make sense to manage as part of the plugin, others may be specific to an installation or even a topic.

Q: Does DFO have department specific thesauri that you manage externally to this plugin?
Would it be helpful to include those in the plugin with a `-Ddfo` profile?

**Comment by ianwallen** [comment]
Jody,

No specific thesauri for DFO at the moment. But there may be some in the future.

Adding a DFO specific thesauri to the plugin is possible however if doing this then we should be willing to accept profiles for all departments and they should be structured in a way that make it easy to identify/manage.  If we add a -D for each department then this could get long if a lot of departments join the project. So for now I would just include them all - not sure if this will cause issues?
I would also suggest that we rename the existing ones so that the ECCC/FGP specific thesauri are named as such and any that are shared between departments are renamed to GC*(government of canada).

**Comment by jodygarnett** [comment]
I actually found a better example today, the managing of XSLT transformations that take content from other schemas into HNAP could be managed as a build profile. ECCC has just such a transform to go from [3.6.x-ec](https://github.com/metadata101/iso19139.ca.HNAP/tree/3.6.x-ec) to [3.10.x](https://github.com/metadata101/iso19139.ca.HNAP/tree/3.10.x).

**Comment by geothorne** [comment]
**ECCC Use Case Example:**
@ianwallen ECCC like many other departments are being asked by TBS to develop a data asset inventory under this there are specific metadata (controlled values) that either ECCC or TBS (to support MAF) are required.

I have been working with the ECCC data asset inventory team to hopefully have our departmental catalogue support the search and discovery of these assets within our department, as a separate publishing end-point vs. FGP or Open Data. However once a departmental data asset has been identified many of them should be planned to be published as an Open Data product/service or map service.

The idea being that data asset inventory is a planned departmental activity to create annual snapshots of data assets to help life cycle manage valued departmental data assets. 
 
So how does this relate to thesauri or to ca.HNAP? Well I am trying to possibly avoid creating a separate  profile outside of HNAP. Ideally a metadata editor could create both an Open Data or FGP metadata record while providing the department data asset inventory information for departmental reporting to TBS (MAF). 
   
So, I guess the question is. "can we manage custom code lists within this git project?" to help deployment of different Canadian catalogues? 

@jodygarnett did I miss something or make it too complicated?

**Comment by jodygarnett** [comment]
I opened this as a discussion, wanted to share the approach I have been successful with thus far.

For the most part I have being using war overlay:

* To provide replacement for webapp/initilization` files like `GC_Org_names.rdf` or `GC_Open_Licenses.rdf` (see [example](https://github.com/GeoCat/experiment-hnap/tree/master/web/src/main/webapp/initialization/settings/thesaurus) )
* To overlay replacement files like `loc/eng/schematron-rules-common.xml` to clarify error messages (for example to reference values in a replacement `GC_Open_Licenses.rdf` file)

**Comment by ianwallen** [comment]
@jodygarnett  The approach you took of overwriting the code list is better than a fork however you still need to manage a separate repository for the overlay.

A lot of the NAP codelist point to Geogratis. I don't believe those can be changed. Are there any cases where we have custom codelists identified in the metadata records as real codelist?  If they are then I believe these codelists are supposed to be placed on a public web site accessible by the people who can access the metadata records.  In these cases, it should be possible to import these codelists as part of the configuration.

Are the codelist that we are discussing here mostly for the helper codelist?  I believe we are using some of these help lists as hacks.  i.e. gmd:useLimitation is a open character string field. Even thought it is open text we are attempting to force the value to be from a list of licenses.  So we are using a help lists to pick the values and the schematron to validate the values.  If this was a true code list then it would be pointing to a publicly available list and I believe it would not be an issue.

In either case, it is still desired to have different helper list for different applications/deployments.

Question: 
Are we looking to have these helper list privately managed?  Or do we want to have them in Metadata 101?
If they are privately managed then it seems like the overlay may be the best approach.

**Comment by jodygarnett** [comment]
Marking this as resolved, it appears customizations can be handled as an overlay, rather than build profiles.

Your feedback above is valid @ianwallen, the use-case above was for canadian, but not government of canada, use. So not all the department names or open data licenses were applicable.
