### ISSUE TITLE
Interesting challenge for non GC_Open_license.rdf use

### ISSUE THREAD

**Issue by jodygarnett** [metadata101/iso19139.ca.HNAP#97]
I have an interesting challenge for non GC use, the file [schematron-rules-non-multilingual.sch#L136-L151](https://github.com/metadata101/iso19139.ca.HNAP/blob/3.10.x/src/main/plugin/iso19139.ca.HNAP/schematron/schematron-rules-non-multilingual.sch#L136-L151)

```xml
    <!-- Use Limitation -->
    <sch:rule context="//gmd:identificationInfo/gmd:MD_DataIdentification
            |//*[@gco:isoType='gmd:MD_DataIdentification']
            |//*[@gco:isoType='srv:SV_ServiceIdentification']">

      <sch:let name="open-licenses" value="document(concat('file:///', replace(concat($thesaurusDir, '/external/thesauri/theme/GC_Open_licenses.rdf'), '\\', '/')))"/>

      <sch:let name="openLicense" value="count(gmd:resourceConstraints/gmd:MD_LegalConstraints/gmd:useLimitation[
               (normalize-space(gco:CharacterString) = $open-licenses//rdf:Description/ns2:prefLabel[@xml:lang=$mainLanguage2char])])" />


      <sch:assert
        test="$openLicense > 0"
      >$loc/strings/OpenLicense</sch:assert>

    </sch:rule>
```

The above rule wants to ensure the record is available as one of the approved open data licenses defined by `GC_Open_licenses.rdf` thesaurus.

Options:

a) Split this into a seperate schematron file, so the check can be disabled as a configuration option

b) Replace `GC_Open_licenses.rdf` with an appropriate license

c) change the `$openLicense` check

d) can we make a configuration options (to send into the schematron)

**Comment by ianwallen** [comment]
I would expect that you would have similar issues with the organization names and other thesaurus?
As this organization is not GC - it sounds like they should be using their own thesaurus - So maybe the schematron needs to be modified so support an option to supply the thesaurus to use.  
It would be similar to option "b)" but instead of replacing GC_Open_licenses.rdf and putting data that is not GC open licenses, it would instead point to Other_Open_licenses.rdf which makes more sense and may avoid future confusion.

**Comment by jodygarnett** [comment]
You can see an experiment here - https://github.com/GeoCat/experiment-hnap
Right now the war overlay over-writes those two files.

We should consider adding options as you describe longer term.

**Comment by jodygarnett** [comment]
Option (b) is working, going to mark this as addressed.
